apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loki-ai-analyzer.fullname" . }}
  labels:
    {{- include "loki-ai-analyzer.labels" . | nindent 4 }}
type: Opaque
data:
  LOKI_ANALYZER_ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicAPIKey | b64enc | quote }}
  LOKI_ANALYZER_SLACK_WEBHOOK_URL: {{ .Values.secrets.slackWebhookURL | b64enc | quote }}
