{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loki-ai-analyzer.fullname" . }}
  labels:
    {{- include "loki-ai-analyzer.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.anthropicAPIKeyKey }}: {{ .Values.secrets.anthropicAPIKey | b64enc | quote }}
  {{ .Values.secrets.slackWebhookURLKey }}: {{ .Values.secrets.slackWebhookURL | b64enc | quote }}
{{- end }}
