package notifier

import (
	"fmt"
	"strings"
	"time"

	"github.com/rs/zerolog"
	"github.com/slack-go/slack"
)

const maxSlackTextLength = 3000

type Notifier struct {
	webhookURL string
	logger     zerolog.Logger
}

func New(webhookURL string, logger zerolog.Logger) *Notifier {
	return &Notifier{
		webhookURL: webhookURL,
		logger:     logger.With().Str("component", "notifier").Logger(),
	}
}

func (n *Notifier) Send(analysisResult string) error {
	blocks := buildBlocks(analysisResult)

	msg := &slack.WebhookMessage{
		Blocks: &slack.Blocks{
			BlockSet: blocks,
		},
	}

	n.logger.Info().Msg("sending analysis report to slack")

	if err := slack.PostWebhook(n.webhookURL, msg); err != nil {
		return fmt.Errorf("post slack webhook: %w", err)
	}

	n.logger.Info().Msg("slack notification sent")
	return nil
}

func buildBlocks(analysisResult string) []slack.Block {
	blocks := []slack.Block{
		slack.NewHeaderBlock(
			slack.NewTextBlockObject(slack.PlainTextType, "Loki Log Analysis Report", false, false),
		),
		slack.NewSectionBlock(
			slack.NewTextBlockObject(
				slack.MarkdownType,
				fmt.Sprintf("*Analysis completed:* %s", time.Now().UTC().Format(time.RFC3339)),
				false, false,
			),
			nil, nil,
		),
		slack.NewDividerBlock(),
	}

	chunks := splitForSlack(analysisResult)
	for _, chunk := range chunks {
		blocks = append(blocks, slack.NewSectionBlock(
			slack.NewTextBlockObject(slack.MarkdownType, chunk, false, false),
			nil, nil,
		))
	}

	blocks = append(blocks, slack.NewDividerBlock())
	blocks = append(blocks, slack.NewContextBlock(
		"",
		slack.NewTextBlockObject(
			slack.MarkdownType,
			"_Generated by Loki AI Analyzer_",
			false, false,
		),
	))

	return blocks
}

func splitForSlack(text string) []string {
	if len(text) <= maxSlackTextLength {
		return []string{text}
	}

	var chunks []string
	lines := strings.Split(text, "\n")
	var current strings.Builder

	for _, line := range lines {
		if current.Len()+len(line)+1 > maxSlackTextLength && current.Len() > 0 {
			chunks = append(chunks, current.String())
			current.Reset()
		}
		current.WriteString(line)
		current.WriteByte('\n')
	}

	if current.Len() > 0 {
		chunks = append(chunks, current.String())
	}

	return chunks
}
